import React, {
  createContext,
  useContext,
  useState,
  useEffect,
  useCallback
} from "react";

// ─── 类型 ──────────────────────────────────────────────────────────────────────
export type Language = "zh-CN" | "en-US";
export type Theme = "light" | "dark" | "system";

export interface AppSettings {
  autoStart: boolean;
  showNotifications: boolean;
  keepHistoryDays: number;
  maxHistoryEntries: number;
  tokenLimit: number;
  language: Language;
  theme: Theme;
}

export interface SettingsContextValue {
  settings: AppSettings;
  updateSettings: (patch: Partial<AppSettings>) => void;
  resetSettings: () => void;
  t: (key: string, vars?: Record<string, string | number>) => string; // 翻译函数（支持插值）
}

// ─── 默认值 ────────────────────────────────────────────────────────────────────
const DEFAULT_SETTINGS: AppSettings = {
  autoStart: false,
  showNotifications: true,
  keepHistoryDays: 30,
  maxHistoryEntries: 200,
  tokenLimit: 1000000,
  language: "zh-CN",
  theme: "light"
};

const SETTINGS_KEY = "claw_app_settings";

// ─── 翻译字典 ──────────────────────────────────────────────────────────────────
type TranslationMap = Record<string, string>;

const translations: Record<Language, TranslationMap> = {
  "zh-CN": {
    // 通用
    "app.name": "WeClaw",
    "nav.claw": "Claw",
    "nav.clawAgent": "Claw",
    "nav.dashboard": "仪表盘",
    "nav.chat": "对话",
    "nav.workflow": "工作流",
    "nav.tasks": "任务",
    "nav.skills": "技能",
    "nav.tools": "工具",
    "nav.models": "模型",
    "nav.workspace": "工作区",
    "nav.history": "历史",
    "nav.settings": "设置",
    // Claw Agent
    "clawAgent.newTaskTitle": "新任务",
    "clawAgent.deleteConfirm": "确定要删除这个任务吗？",
    "clawAgent.tasks": "任务",
    "clawAgent.taskList": "任务列表",
    "clawAgent.noTasks": "暂无任务",
    "clawAgent.newTask": "新任务",
    "clawAgent.retry": "重试",
    "clawAgent.delete": "删除",
    "clawAgent.completed": "完成",
    "clawAgent.steps": "步",
    "clawAgent.planMode": "Plan 模式",
    "clawAgent.plan": "计划",
    "clawAgent.placeholderNoTask": "请先创建任务",
    "clawAgent.placeholder": "描述你想要完成的任务...",
    "clawAgent.noTaskSelected": "请选择一个任务或创建新任务",
    "clawAgent.planning": "正在分析任务并制定计划...",
    "clawAgent.waitingForInput": "描述你想要完成的任务",
    "clawAgent.goal": "目标",
    "clawAgent.error": "错误",
    "clawAgent.output": "输出",
    "clawAgent.finalResult": "最终结果",
    "clawAgent.executing": "执行中...",
    "clawAgent.openFolder": "打开目录",
    "clawAgent.pause": "暂停",
    "clawAgent.sessionTokens": "本次",
    "clawAgent.totalTokens": "总计",
    "clawAgent.status.planning": "规划中",
    "clawAgent.status.idle": "空闲",
    "clawAgent.status.running": "执行中",
    "clawAgent.status.paused": "已暂停",
    "clawAgent.status.done": "已完成",
    "clawAgent.status.failed": "失败",
    "clawAgent.status.cancelled": "已取消",
    "clawAgent.prompt.analyze": "分析这个任务并制定执行计划",
    "clawAgent.prompt.search": "搜索相关信息",
    "clawAgent.prompt.createFile": "创建一个文件",
    "clawAgent.prompt.runCode": "执行一些代码",
    "clawAgent.prompt.summarize": "总结当前结果",
    "sidebar.expand": "展开侧边栏",
    "sidebar.collapse": "收起侧边栏",
    // Login
    "login.title": "登录",
    "login.username": "用户名",
    "login.usernamePlaceholder": "请输入用户名",
    "login.password": "密码",
    "login.passwordPlaceholder": "请输入密码",
    "login.confirmPassword": "确认密码",
    "login.confirmPasswordPlaceholder": "请再次输入密码",
    "login.submit": "登录",
    "login.errorEmpty": "请输入用户名和密码",
    "login.errorMismatch": "两次输入的密码不一致",
    "login.errorShort": "密码长度至少4位",
    "login.errorExists": "用户名已存在",
    "login.errorFailed": "用户名或密码错误",
    "login.switchRegister": "没有账号？点击注册",
    "login.defaultHint": "默认账号: admin / admin123",
    "register.title": "注册新账号",
    "register.submit": "注册",
    "register.switchLogin": "已有账号？点击登录",
    // Sidebar user menu
    "sidebar.userMenu.history": "历史记录",
    "sidebar.userMenu.models": "模型配置",
    "sidebar.userMenu.tools": "工具管理",
    "sidebar.userMenu.settings": "设置",
    "sidebar.userMenu.logout": "退出登录",
    "sidebar.userMenu.changePassword": "修改密码",
    // Account
    "settings.account": "账号与安全",
    "settings.accountHint": "当前登录账号",
    "settings.oldPassword": "当前密码",
    "settings.oldPasswordPlaceholder": "请输入当前密码",
    "settings.newPassword": "新密码",
    "settings.newPasswordPlaceholder": "请输入新密码",
    "settings.confirmPassword": "确认密码",
    "settings.confirmPasswordPlaceholder": "请再次输入新密码",
    "settings.changePassword": "修改密码",
    "settings.passwordErrorEmpty": "请填写所有密码字段",
    "settings.passwordErrorMismatch": "两次输入的新密码不一致",
    "settings.passwordErrorShort": "新密码长度至少4位",
    "settings.passwordErrorWrong": "当前密码错误",
    "settings.passwordSuccess": "密码修改成功",
    // Settings
    "settings.title": "设置",
    "settings.subtitle": "管理应用程序设置和偏好",
    "settings.app": "应用程序设置",
    "settings.autoStart": "开机自动启动",
    "settings.notifications": "显示通知",
    "settings.language": "语言",
    "settings.theme": "主题",
    "settings.theme.light": "浅色主题",
    "settings.theme.dark": "深色主题",
    "settings.theme.system": "跟随系统",
    "settings.historyDays": "历史记录保留天数",
    "settings.maxEntries": "最大历史记录条数",
    "settings.tokenLimit": "Token 限额（每日）",
    "settings.data": "数据管理",
    "settings.security": "安全设置",
    "settings.advanced": "高级设置",
    "settings.about": "关于",
    "settings.export": "导出历史记录",
    "settings.exporting": "导出中...",
    "settings.clearHistory": "清除历史记录",
    "settings.clearing": "清除中...",
    "settings.clearCache": "清除缓存",
    "settings.reset": "重置所有设置",
    "settings.devtools": "打开开发者工具",
    "settings.managePerms": "管理权限 →",
    "settings.resetConfirm": "确定要重置所有设置为默认值吗？此操作不可撤销。",
    "settings.resetDone": "设置已重置为默认值",
    "settings.clearConfirm": "确定要清除所有历史记录吗？此操作不可撤销。",
    "settings.clearDone": "历史记录已清除",
    "settings.clearCacheConfirm":
      "确定要清除缓存吗？这将删除所有临时文件，但不会影响配置和历史记录。",
    "settings.clearCacheDone": "缓存已清除",
    "settings.exportDone": "历史记录导出成功！文件已保存到下载目录。",
    "settings.exportFail": "导出失败，请重试",
    "settings.clearFail": "清除失败，请重试",
    // Dashboard
    "dashboard.title": "仪表盘",
    "dashboard.subtitle": "欢迎使用 WeClaw Client，以下是当前项目概览",
    "dashboard.workflow": "工作流概览",
    "dashboard.tasks": "任务管理概览",
    "dashboard.chat": "对话数据概览",
    "dashboard.history": "操作记录概览",
    "dashboard.noWorkflow": '暂无工作流，点击"工作流"页面创建',
    "dashboard.noTask": "暂无任务",
    "dashboard.noHistory": "暂无操作记录",
    "dashboard.noChat": "暂无对话记录",
    "dashboard.skills": "技能库概览",
    "dashboard.tools": "工具管理概览",
    "dashboard.claw": "Claw 概览",
    "dashboard.noClaw": "暂无 Claw 任务",
    "dashboard.claw.running": "进行中",
    "dashboard.claw.planning": "规划中",
    "dashboard.claw.steps": "步",
    "dashboard.justNow": "刚刚",
    "dashboard.minutesAgo": "分钟前",
    "dashboard.hoursAgo": "小时前",
    "dashboard.daysAgo": "天前",
    "dashboard.noSkills": "暂无技能",
    "dashboard.noTools": "暂无工具",
    "dashboard.skills.categories": "分类数",
    "dashboard.skills.builtin": "内置",
    "dashboard.skills.used": "次使用",
    "dashboard.tools.readWrite": "读写权限",
    "dashboard.tools.disabled": "已禁用",
    "dashboard.tools.securityHint": "存在读写权限工具，请确认已了解风险。",
    "dashboard.total": "共",
    "dashboard.enabled": "已启用",
    "dashboard.disabled": "已停用",
    "dashboard.lastRun": "最近运行",
    "dashboard.trigger.manual": "手动",
    "dashboard.trigger.scheduled": "定时",
    "dashboard.trigger.file_change": "文件变更",
    "dashboard.trigger.api_call": "API 调用",
    "dashboard.status.success": "成功",
    "dashboard.status.failed": "失败",
    "dashboard.tokenUsage": "Token 消耗",
    "dashboard.today": "今日",
    "dashboard.totalTokens": "累计消耗",
    "dashboard.used": "已用",
    "dashboard.remaining": "剩余",
    "dashboard.status.running": "运行中",
    "dashboard.status.pending": "待处理",
    "dashboard.status.in_progress": "进行中",
    "dashboard.status.completed": "已完成",
    "dashboard.status.cancelled": "已取消",
    "dashboard.priority.low": "低",
    "dashboard.priority.medium": "中",
    "dashboard.priority.high": "高",
    "dashboard.priority.critical": "紧急",
    "dashboard.op.chat_message": "对话消息",
    "dashboard.op.model_switch": "模型切换",
    "dashboard.op.workspace_add": "工作区添加",
    "dashboard.op.file_read": "文件读取",
    "dashboard.op.file_write": "文件写入",
    "dashboard.op.code_run": "代码执行",
    "dashboard.time.justNow": "刚刚",
    "dashboard.time.minutesAgo": "分钟前",
    "dashboard.time.hoursAgo": "小时前",
    "dashboard.time.daysAgo": "天前",
    // Workflow
    "workflow.title": "工作流自动化",
    "workflow.subtitle": "创建和管理自动化工作流程",
    "workflow.create": "创建工作流",
    "workflow.noSteps": "暂无步骤，请添加工作流步骤",
    "workflow.stepsPreview": "工作流步骤预览",
    "workflow.outputTitle": "执行输出",
    "workflow.outputSubtitle": "查看工作流的执行历史和输出结果",
    "workflow.total": "总工作流数",
    "workflow.enabled": "已启用",
    "workflow.scheduled": "定时任务",
    "workflow.successRate": "成功率",
    "workflow.newTitle": "新建工作流",
    "workflow.nameLabel": "工作流名称 *",
    "workflow.createBtn": "新建工作流",
    "workflow.createFormTitle": "创建工作流",
    "workflow.nameLabel2": "工作流名称 *",
    "workflow.namePlaceholder": "例如: 代码审查自动化",
    "workflow.triggerLabel": "触发方式",
    "workflow.trigger.manual": "手动触发",
    "workflow.trigger.scheduled": "定时任务 (Cron)",
    "workflow.trigger.file_change": "文件变更",
    "workflow.trigger.api_call": "API调用",
    "workflow.cronConfigLabel": "Cron调度配置",
    "workflow.descLabel": "工作流描述",
    "workflow.descPlaceholder": "描述工作流的用途和功能",
    "workflow.stepsLabel": "工作流步骤",
    "workflow.addStep": "添加步骤",
    "workflow.enabledLabel": "启用工作流",
    "workflow.cancel": "取消",
    "workflow.saveCreate": "创建工作流",
    "workflow.empty": "暂无工作流",
    "workflow.tagEnabled": "已启用",
    "workflow.tagDisabled": "已禁用",
    "workflow.status.success": "成功",
    "workflow.status.failed": "失败",
    "workflow.status.running": "运行中",
    "workflow.stepsCount": "{n} 个步骤",
    "workflow.lastRun": "最后运行",
    "workflow.triggerInfo.scheduled": "定时",
    "workflow.triggerInfo.manual": "手动触发",
    "workflow.triggerInfo.file_change": "文件变更触发",
    "workflow.triggerInfo.api_call": "API触发",
    "workflow.runningBtn": "运行中",
    "workflow.runNow": "立即运行",
    "workflow.viewOutput": "查看执行输出",
    "workflow.disableBtn": "禁用",
    "workflow.enableBtn": "启用",
    "workflow.deleteTitle": "删除工作流",
    "workflow.deleteConfirm": "确定要删除这个工作流吗？",
    "workflow.requiredName": "请输入工作流名称",
    "workflow.stepPrefix": "步骤",
    "workflow.stepDefaultName": "新步骤",
    "workflow.stepDefaultDesc": "描述这个步骤的功能",
    "workflow.editStep": "编辑步骤",
    // CronConfig labels
    "workflow.cron.minute": "分钟",
    "workflow.cron.hour": "小时",
    "workflow.cron.day": "日期",
    "workflow.cron.month": "月份",
    "workflow.cron.week": "星期",
    "workflow.cron.exprLabel": "Cron表达式:",
    "workflow.cron.examplesLabel": "示例:",
    "workflow.cron.example1": "工作日每天9:00",
    "workflow.cron.example2": "每2小时",
    // OutputViewer labels
    "workflow.output.title": "执行输出",
    "workflow.output.lastRunTime": "最后运行时间",
    "workflow.output.runStatus": "运行状态",
    "workflow.output.stepsCount": "步骤数量",
    "workflow.output.output": "执行输出",
    "workflow.output.steps": "执行步骤",
    "workflow.output.stepStatus": "状态: 已完成",
    "workflow.output.noRecord": "暂无执行记录",
    // Workflow 新增 key
    "workflow.trigger.webhook": "Webhook 触发",
    "workflow.triggerInfo.webhook": "Webhook 触发",
    "workflow.editBtn": "编辑工作流",
    "workflow.saveBtn": "保存",
    "workflow.backList": "返回列表",
    "workflow.nodeLibrary": "节点库",
    "workflow.fitView": "适配视图",
    "workflow.canvasEmpty": "画布为空",
    "workflow.canvasEmptyHint":
      "从左侧节点库拖拽节点到画布，或使用连线连接节点",
    "workflow.node.label": "节点名称",
    "workflow.node.description": "节点描述",
    "workflow.node.save": "保存节点",
    "workflow.node.delete": "删除节点",
    "workflow.node.deleteConfirm": "确定要删除这个节点吗？",
    "workflow.node.startTip": "开始节点是工作流的入口，无需配置。",
    "workflow.node.model": "模型",
    "workflow.node.prompt": "提示词",
    "workflow.node.temperature": "温度",
    "workflow.node.outputVar": "输出变量",
    "workflow.node.condition": "条件表达式",
    "workflow.node.conditionTip":
      "支持 {{变量名}} 引用上下文变量，例如：{{score}} > 80",
    "workflow.node.operation": "操作类型",
    "workflow.node.filePath": "文件路径",
    "workflow.node.fileContent": "文件内容",
    "workflow.node.language": "代码语言",
    "workflow.node.code": "代码内容",
    "workflow.node.taskTitle": "任务标题",
    "workflow.node.taskDesc": "任务描述",
    "workflow.node.priority": "优先级",
    "workflow.node.channel": "通知渠道",
    "workflow.node.message": "消息内容",
    "workflow.node.recipients": "收件人",
    "workflow.node.url": "目标 URL",
    "workflow.node.selector": "CSS 选择器",
    "workflow.node.dataOp": "数据操作",
    "workflow.node.inputVar": "输入变量",
    "workflow.node.script": "处理脚本",
    "workflow.node.command": "命令",
    "workflow.node.workingDir": "工作目录",
    "workflow.node.timeout": "超时 (秒)",
    "workflow.node.skillId": "技能 ID",
    "workflow.node.inputs": "输入参数 (JSON)",
    "workflow.node.branches": "分支数量",
    "workflow.node.waitStrategy": "等待策略",
    "workflow.node.iterateVar": "迭代变量",
    "workflow.node.itemVar": "当前项变量名",
    "workflow.node.maxIterations": "最大迭代次数",
    "workflow.node.endMessage": "结束消息",
    "workflow.node.selectTool": "选择工具",
    "workflow.node.toolParams": "工具参数",
    "workflow.node.toolNoParams": "该工具无需配置参数",
    "workflow.node.noEnabledTools":
      "暂无已启用的工具，请先在工具管理中启用工具",
    "workflow.node.toolUncategorized": "未分类",
    "workflow.moreSettings": "更多设置",
    "workflow.collapseSettings": "收起设置",
    "workflow.expandSettings": "展开设置",
    // Tasks
    "tasks.title": "任务管理",
    "tasks.subtitle": "管理您的项目任务和工作流程",
    "tasks.create": "新建任务",
    "tasks.statusAll": "全部状态",
    "tasks.priorityAll": "全部优先级",
    "tasks.status": "状态",
    "tasks.priority": "优先级",
    "tasks.titlePlaceholder": "请输入任务标题",
    "tasks.noTasks": "暂无任务",
    "tasks.responsible": "负责人",
    "tasks.allResponsible": "全部负责人",
    "tasks.systemAdmin": "系统管理员",
    "tasks.currentUser": "当前用户",
    "tasks.totalTasks": "共 {count} 个任务",
    "tasks.createNew": "创建新任务",
    "tasks.taskTitle": "任务标题 *",
    "tasks.taskDesc": "任务描述",
    "tasks.estimatedHours": "预计工时（小时）",
    "tasks.dueDate": "截止日期",
    "tasks.tags": "标签（逗号分隔）",
    "tasks.exampleTags": "例如: 前端, bug, 功能",
    "tasks.cancel": "取消",
    "tasks.createBtn": "创建任务",
    "tasks.expandDesc": "任务描述",
    "tasks.details": "任务详情",
    "tasks.creator": "创建人：",
    "tasks.assignee": "负责人：",
    "tasks.deadline": "截止时间：",
    "tasks.estimatedTime": "预计工时：",
    "tasks.actualTime": "实际工时：",
    "tasks.hours": "小时",
    "tasks.tagsNotes": "标签和备注",
    "tasks.dependency": "依赖任务",
    "tasks.dependencyCount": "依赖 {count} 个其他任务",
    "tasks.markComplete": "标记完成",
    "tasks.edit": "编辑",
    "tasks.delete": "删除",
    "tasks.deleteConfirm": "确定要删除这个任务吗？",
    "tasks.stats": "任务统计",
    "tasks.totalCount": "总任务数",
    "tasks.inProgress": "进行中",
    "tasks.completed": "已完成",
    "tasks.pending": "待处理",
    // Skills
    "skills.title": "技能库",
    "skills.subtitle": "管理 AI 助手可调用的技能，支持新建、编辑、导入和分享",
    "skills.importExport": "导入 / 导出",
    "skills.newSkill": "新建技能",
    "skills.allSkills": "全部技能",
    "skills.enabled": "已启用",
    "skills.custom": "自定义",
    "skills.searchPlaceholder": "搜索技能名称、描述或标签...",
    "skills.categoryAll": "全部",
    "skills.cat.productivity": "效率",
    "skills.cat.coding": "编程",
    "skills.cat.writing": "写作",
    "skills.cat.analysis": "分析",
    "skills.cat.communication": "沟通",
    "skills.cat.custom": "自定义",
    "skills.notFound": '未找到与"{q}"相关的技能',
    "skills.emptyCategory": "该分类暂无技能",
    "skills.builtin": "内置",
    "skills.unnamed": "未命名技能",
    "skills.noDesc": "暂无描述",
    "skills.usageCount": "次",
    "skills.usedToast": "已应用技能：",
    "skills.btnUse": "使用技能",
    "skills.btnEdit": "编辑",
    "skills.btnExport": "导出",
    "skills.btnDelete": "删除",
    "skills.toggleEnable": "点击禁用",
    "skills.toggleDisable": "点击启用",
    "skills.deleteConfirm": "确定要删除该技能吗？此操作不可恢复。",
    "skills.editor.titleEdit": "编辑技能",
    "skills.editor.titleNew": "新建技能",
    "skills.editor.tabBasic": "基本信息",
    "skills.editor.tabContent": "技能内容",
    "skills.editor.name": "技能名称",
    "skills.editor.namePlaceholder": "如：生成周报",
    "skills.editor.nameRequired": "技能名称不能为空",
    "skills.editor.desc": "描述",
    "skills.editor.descPlaceholder": "简要描述技能的用途",
    "skills.editor.category": "分类",
    "skills.editor.version": "版本",
    "skills.editor.author": "作者",
    "skills.editor.authorPlaceholder": "作者名称",
    "skills.editor.sourceUrl": "来源 URL（可选）",
    "skills.editor.tags": "标签",
    "skills.editor.tagsPlaceholder": "输入标签后按 Enter",
    "skills.editor.content": "技能内容（提示词 / 指令）",
    "skills.editor.contentHint":
      "定义 AI 接收到该技能后的行为，支持 Markdown 格式的提示词。",
    "skills.editor.contentPlaceholder": "请描述该技能的详细提示词或指令...",
    "skills.editor.contentRequired": "技能内容不能为空",
    "skills.editor.chars": "字符",
    "skills.editor.cancel": "取消",
    "skills.editor.saveEdit": "保存修改",
    "skills.editor.saveNew": "创建技能",
    "skills.ie.title": "导入 / 导出技能",
    "skills.ie.exportTitle": "导出技能包",
    "skills.ie.exportDesc":
      "将所有自定义技能（{n} 个）导出为 JSON 文件，可分享给他人。",
    "skills.ie.exportBtn": "导出全部自定义技能",
    "skills.ie.importFileTitle": "从本地文件导入",
    "skills.ie.importFileBtn": "选择技能包文件（.json）",
    "skills.ie.importUrlTitle": "从 URL 导入（社区分享）",
    "skills.ie.importUrlBtn": "导入",
    "skills.ie.importing": "获取中...",
    "skills.ie.fetchFail": "获取失败：",
    "skills.ie.invalidFormat": "文件格式无效，请检查是否为合法的技能包 JSON",
    "skills.ie.noImportable": "技能包中没有可导入的技能（内置技能会被跳过）",
    "skills.ie.importSuccess": "导入成功",
    "skills.ie.importCount": "，共 {n} 个技能",
    "skills.ie.close": "关闭",
    // Tools
    "tools.title": "工具管理",
    "tools.subtitle": "管理 AI 可调用的工具，配置权限和自定义接口",
    "tools.newTool": "新建工具",
    "tools.allTools": "全部工具",
    "tools.available": "可用工具",
    "tools.readOnly": "只读工具",
    "tools.disabled": "已禁用",
    "tools.searchPlaceholder": "搜索工具名称、描述或分组...",
    "tools.typeAll": "全部",
    "tools.type.builtin": "内置",
    "tools.type.script": "脚本",
    "tools.type.api": "API",
    "tools.perm.read_only": "只读",
    "tools.perm.read_write": "读写",
    "tools.perm.disabled": "已禁用",
    "tools.notFound": '未找到"{q}"相关工具',
    "tools.emptyType": "该类型暂无工具",
    "tools.builtin": "内置",
    "tools.unnamed": "未命名工具",
    "tools.noDesc": "暂无描述",
    "tools.paramCount": "个参数",
    "tools.callCount": "调用",
    "tools.callCountUnit": "次",
    "tools.permLabel": "权限说明：",
    "tools.permReadOnlyDesc": "仅允许读取数据，不可修改",
    "tools.permReadWriteDesc": "允许读取和写入数据",
    "tools.permDisabledDesc": "禁止 AI 调用此工具",
    "tools.toggleEnable": "点击禁用",
    "tools.toggleDisable": "点击启用",
    "tools.btnEdit": "编辑",
    "tools.btnDelete": "删除",
    "tools.deleteConfirm": "确定要删除该工具吗？此操作不可恢复。",
    "tools.warnTitle": "个工具处于「读写」权限",
    "tools.warnDesc":
      "读写工具可能对文件系统或外部服务造成修改，请确保仅授权受信任的工具。",
    "tools.warnSetReadOnly": "全部改为只读",
    "tools.editor.titleEdit": "编辑工具",
    "tools.editor.titleNew": "新建工具",
    "tools.editor.tabBasic": "基本信息",
    "tools.editor.tabParams": "参数",
    "tools.editor.tabApi": "API 配置",
    "tools.editor.tabScript": "脚本内容",
    "tools.editor.icon": "图标",
    "tools.editor.name": "工具名称",
    "tools.editor.namePlaceholder": "如：HTTP 请求",
    "tools.editor.nameRequired": "工具名称不能为空",
    "tools.editor.type": "工具类型",
    "tools.editor.desc": "描述",
    "tools.editor.descPlaceholder": "描述工具的功能和适用场景",
    "tools.editor.category": "分组",
    "tools.editor.categoryPlaceholder": "如：文件系统",
    "tools.editor.permission": "默认权限",
    "tools.editor.paramsHint": "定义调用该工具时所需的参数",
    "tools.editor.addParam": "添加参数",
    "tools.editor.noParams": "暂未定义参数，点击添加参数开始配置",
    "tools.editor.paramNum": "参数 #",
    "tools.editor.paramName": "参数名",
    "tools.editor.paramType": "类型",
    "tools.editor.paramDesc": "描述",
    "tools.editor.paramDescPlaceholder": "参数说明",
    "tools.editor.paramRequired": "必填",
    "tools.editor.paramDefault": "默认值（可选）",
    "tools.editor.apiEndpoint": "API 地址",
    "tools.editor.apiEndpointRequired": "API 地址不能为空",
    "tools.editor.apiMethod": "HTTP 方法",
    "tools.editor.apiHeaders": "请求头（JSON 格式，可选）",
    "tools.editor.scriptContent": "脚本内容",
    "tools.editor.scriptContentRequired": "脚本内容不能为空",
    "tools.editor.scriptHint":
      "支持 Shell / Python / Node.js 脚本，参数通过环境变量传入。",
    "tools.editor.cancel": "取消",
    "tools.editor.saveEdit": "保存修改",
    "tools.editor.saveNew": "创建工具",
    // History
    "history.title": "历史记录",
    "history.subtitle": "查看所有操作的详细记录和安全日志",
    "history.refresh": "刷新记录",
    "history.syncBtn": "定时同步",
    "history.syncEnabled": "定时同步已启用",
    "history.syncFailed": "同步失败",
    "history.syncNow": "立即同步",
    "history.syncConfig": "定时同步配置",
    "history.noRecords": "暂无操作记录",
    // ModelConfig
    "models.title": "模型配置",
    "models.subtitle": "配置和管理您的AI模型API连接",
    "models.add": "添加模型",
    "models.addNew": "添加新模型",
    "models.nameLabel": "模型名称 *",
    "models.typeLabel": "模型类型 *",
    "models.endpointLabel": "API端点 *",
    "models.keyLabel": "API密钥",
    "models.setDefault": "设为默认模型",
    "models.namePlaceholder": "例如: GPT-4",
    "models.endpointPlaceholder":
      "例如: https://api.openai.com/v1/chat/completions",
    "models.keyPlaceholder": "请输入API密钥",
    "models.keyEditPlaceholder": "如需更新密钥请填写",
    "models.cancel": "取消",
    "models.createBtn": "创建模型",
    "models.editTitle": "编辑模型",
    "models.editNameLabel": "模型名称 *",
    "models.editTypeLabel": "模型类型 *",
    "models.editEndpointLabel": "API端点 *",
    "models.editKeyLabel": "API密钥",
    "models.editSetDefault": "设为默认模型",
    "models.saveBtn": "保存更改",
    "models.listTitle": "已配置的模型",
    "models.empty": '暂无模型配置，点击右上角"添加模型"开始配置',
    "models.tagDefault": "默认",
    "models.tagCurrent": "当前使用",
    "models.titleSetDefault": "设为默认",
    "models.titleEdit": "编辑",
    "models.titleDelete": "删除",
    "models.titleUse": "立即使用",
    "models.deleteConfirm": "确定要删除这个模型配置吗？",
    "models.deleteSuccess": "模型配置已删除",
    "models.deleteFail": "删除失败，请重试",
    "models.deleteError": "删除失败，请检查控制台",
    "models.saveRequired": "请填写模型名称和API端点",
    "models.saveSuccess": "模型配置已保存",
    "models.saveFail": "保存失败，请重试",
    "models.createSuccess": "模型配置已创建",
    "models.createFail": "创建失败，请重试",
    "models.setDefaultSuccess": "已设为默认模型",
    "models.type.custom": "自定义API",
    // 文件上传接口配置
    "models.fileUploadEndpointLabel": "文件上传接口",
    "models.fileUploadEndpointPlaceholder": "例如: https://api.deepseek.com/v1/files",
    "models.fileUploadKeyLabel": "文件上传API密钥",
    "models.fileUploadKeyPlaceholder": "如与主密钥不同请填写",
    // Workspace
    "workspace.title": "工作区间管理",
    "workspace.subtitle": "设置和管理安全工作区间，确保操作权限控制",
    "workspace.current": "当前工作区间",
    "workspace.setTitle": "工作区间已设置",
    "workspace.setDesc": "所有操作将被限制在该目录内，超出权限的操作将被记录。",
    "workspace.name": "工作区间名称",
    "workspace.path": "路径",
    "workspace.createdAt": "创建时间",
    "workspace.status": "状态",
    "workspace.active": "已激活",
    "workspace.change": "更改工作区间",
    "workspace.clear": "清除工作区间",
    "workspace.noSet": "工作区间未设置",
    "workspace.noSetDesc": "请设置工作区间以启用权限控制功能。",
    "workspace.setBtn": "设置工作区间",
    "workspace.testTool": "权限测试工具",
    "workspace.testPath": "测试路径",
    "workspace.testing": "测试中...",
    "workspace.testBtn": "测试权限",
    "workspace.allowed": "允许访问",
    "workspace.denied": "拒绝访问",
    "workspace.testPathHint":
      "输入任意路径，测试该路径是否在当前工作区间内（是否具有操作权限）",
    "workspace.testPathPlaceholder": "例如: /Users/username/Documents/project",
    "workspace.securityTitle": "安全说明",
    "workspace.permControl": "权限控制",
    "workspace.permControlDesc":
      "设置工作区间后，所有文件操作（读取、写入、修改）将被限制在该目录内。尝试访问工作区间外的文件将触发安全警告并被记录。",
    "workspace.opRecord": "历史记录",
    "workspace.opRecordDesc":
      '所有操作（包括权限检查结果）都会被记录到本地历史中，您可以在"操作记录"页面查看所有操作的详细记录。',
    "workspace.securityAdvice": "安全建议",
    "workspace.securityAdviceDesc":
      "1. 建议将工作区间设置为项目专属目录\n2. 定期检查操作记录记录\n3. 仅授予必要的最小权限\n4. 使用强密码保护API密钥",
    "workspace.pathInside": "路径在工作区间内",
    "workspace.pathOutside": "路径不在工作区间内",
    "workspace.testFailed": "测试失败，请检查路径格式",
    "workspace.clearConfirm":
      "确定要清除工作区间设置吗？清除后需要重新设置才能进行操作。",
    "workspace.clearDone": "工作区间已清除，请重新设置",
    "workspace.pathMustBe": "该路径必须位于工作区间内：",
    "workspace.inputPath": "请输入要测试的路径",
    // History (extra)
    "history.syncBtn2": "定时同步",
    "history.refreshBtn": "刷新记录",
    "history.filterType": "筛选类型",
    "history.filterAll": "所有记录",
    "history.filterDenied": "权限拒绝记录",
    "history.filterSuccess": "成功操作",
    "history.filterWarning": "警告操作",
    "history.filterError": "错误操作",
    "history.searchLabel": "搜索关键词",
    "history.searchPlaceholder": "搜索操作类型、目标或权限检查",
    "history.statsLabel": "统计信息",
    "history.totalRecords": "总记录",
    "history.successRecords": "成功",
    "history.deniedRecords": "权限拒绝",
    "history.loading": "正在加载历史记录...",
    "history.empty": "暂无历史记录",
    "history.showCount": "共 {count} 条记录",
    "history.maxCount": "仅显示最近 200 条记录",
    "history.pageInfo": "第 {page} / {total} 页，每页 {size} 条",
    "history.prevPage": "上一页",
    "history.nextPage": "下一页",
    "history.pageSizeLabel": "每页显示",
    "history.pageUnit": "条",
    "history.opTarget": "操作目标",
    "history.permCheck": "权限检查",
    "history.opStatus": "操作状态",
    "history.details": "详细信息",
    "history.noDetails": "暂无详细信息",
    "history.fullTimestamp": "完整时间戳",
    "history.infoTitle": "历史记录说明",
    "history.infoContent": "记录内容",
    "history.infoContentDesc":
      "系统会记录所有关键操作，包括：文本处理、文件访问、权限检查、模型配置变更和工作区间变更。每条记录包含时间戳、操作类型、目标、权限检查结果和详细参数。",
    "history.securityMonitor": "安全监控",
    "history.securityMonitorDesc":
      '重点关注"权限拒绝"记录，这些记录表明有尝试访问工作区间外的操作。定期检查这些记录有助于发现潜在的安全问题。',
    "history.syncDesc": "定时同步",
    "history.syncDescContent":
      '点击"定时同步"按钮可配置自动将操作记录同步到远端服务器。支持间隔模式（每 N 分钟）和 Cron 表达式两种规则，支持 Bearer Token、Basic Auth、API Key 三种认证方式。配置会持久化保存在本地，应用重启后自动恢复定时任务。',
    "history.retentionTitle": "记录保留",
    "history.retentionDesc":
      "历史记录保存在本地 SQLite 数据库中，仅保留最近 200 条记录以防止数据库过大。如需导出或备份历史记录，请访问设置页面。",
    "history.syncConfigTitle": "定时同步配置",
    "history.syncEnabled2": "定时同步已启用",
    "history.target": "目标：",
    "history.notSet": "（未设置）",
    "history.lastSync": "上次：",
    "history.frequency": "频率：",
    "history.syncFailed2": "同步失败",
    "history.syncing": "同步中…",
    "history.syncNow2": "立即同步",
    "history.basicConfig": "基础配置",
    "history.enableSync": "启用定时同步",
    "history.serverUrl": "服务器地址",
    "history.serverUrlPlaceholder": "https://your-server.com/api/history/sync",
    "history.serverUrlHint": "将以 POST 请求发送 JSON 数据到此地址",
    "history.authType": "认证方式",
    "history.authNone": "无认证",
    "history.authBearer": "Bearer Token",
    "history.authBasic": "Basic Auth",
    "history.authApiKey": "API Key（自定义 Header）",
    "history.headerName": "Header 名称",
    "history.apiKeyValue": "API Key 值",
    "history.username": "用户名",
    "history.password": "密码",
    "history.scheduleRules": "定时规则",
    "history.ruleType": "规则类型",
    "history.intervalMode": "间隔模式",
    "history.cronMode": "Cron 表达式",
    "history.syncInterval": "同步间隔",
    "history.minutes": "分钟",
    "history.cronPreset.daily0": "每天0点",
    "history.cronPreset.daily8": "每天8点",
    "history.cronHint": "（分 时 日 月 周）",
    "history.syncOnStartup": "启动时立即同步",
    "history.syncOnStartupHint": "应用启动时触发一次同步",
    "history.advancedOptions": "高级选项",
    "history.maxSyncRecords": "每次同步最大记录数",
    "history.testSync": "立即测试同步",
    "history.cancel": "取消",
    "history.saveConfig": "保存配置",
    "history.configSaved": "配置已保存",
    "history.syncLogs": "同步日志（最近 {count} 条）",
    "history.notEnabled": "未启用",
    "history.neverSync": "从未同步",
    "history.everyHours": "每 {n} 小时",
    "history.everyMinutes": "每 {n} 分钟",
    "history.noServerConfig": "服务器地址未配置，跳过同步",
    "history.syncSuccessMsg": "成功同步 {count} 条记录",
    "history.syncFailHttp": "同步失败：HTTP {status} {statusText}",
    "history.syncException": "同步异常：{msg}",
    "history.opType.text_processing": "文本处理",
    "history.opType.file_access": "文件访问",
    "history.opType.permission_check": "权限检查",
    "history.opType.model_config": "模型配置",
    "history.opType.workspace_change": "工作区间变更",
    "history.opType.unknown": "未知操作",
    // Settings extra (replacing inline ternaries)
    "settings.dataLocalNote":
      "所有数据都保存在本地，确保您的隐私和安全。导出和清除操作仅影响本地数据，不会影响云端配置。",
    "settings.securityTitle2": "安全建议",
    "settings.securityItem1": "定期检查操作记录记录中的权限拒绝记录",
    "settings.securityItem2": "确保工作区间设置正确，避免误操作",
    "settings.securityItem3": "定期导出重要数据作为备份",
    "settings.securityItem4": "使用强密码保护API密钥",
    "settings.appPerms": "应用程序权限",
    "settings.appPermsDesc": "查看和管理应用程序权限",
    "settings.resetTitle": "重置所有设置",
    "settings.resetDesc": "将所有设置恢复为默认值，不会影响您的数据",
    "settings.devtoolsTitle": "开发者工具",
    "settings.devtoolsDesc": "打开开发者工具进行调试",
    "settings.aboutTitle": "关于",
    "settings.versionLabel": "版本号",
    "settings.frameworkLabel": "框架版本",
    "settings.frontendLabel": "前端框架",
    "settings.aboutDesc":
      "WeClaw Client 是一个跨平台的AI助手桌面应用程序，支持模型选择和自定义配置，提供安全的工作区间权限控制，并记录所有操作记录用于安全审计。",
    "settings.copyright": "隐私政策 · 服务条款",
    // Chat
    "chat.newConversation": "新建对话",
    "chat.selectConversation": "选择对话",
    "chat.startNew": "开始新对话",
    "chat.startChat": "开始对话",
    "chat.startChatHint": "输入消息开始与AI对话",
    "chat.selectOrCreate": "选择或创建对话",
    "chat.selectOrCreateHint": '从左侧选择一个对话，或点击"+"创建新对话',
    "chat.conversationList": "对话列表",
    "chat.searchPlaceholder": "搜索对话...",
    "chat.filterAll": "全部",
    "chat.noMatch": "未找到匹配的对话",
    "chat.clearFilter": "清除筛选",
    "chat.noConversation": "暂无对话",
    "chat.deleteConversation": "删除对话",
    "chat.deleteConfirm": "确定要删除这个对话吗？删除后无法恢复。",
    "chat.modelLabel": "模型:",
    "chat.workspaceLabel": "工作区:",
    "chat.online": "在线",
    "chat.selectModel": "请选择模型",
    "chat.uploadImage": "上传图片（支持粘贴/拖拽）",
    "chat.uploadFile": "上传文件",
    "chat.imageBtn": "图片",
    "chat.fileBtn": "文件",
    "chat.newChatBtn": "新对话",
    "chat.removeAttachment": "移除",
    "chat.dropHint": "松开以添加附件",
    "chat.attachmentsCount": "{n} 个附件",
    "chat.sendBtn": "发送（Enter）",
    "chat.fileSizeExceeded": '文件 "{name}" 超过 20MB 限制，已跳过。',
    "chat.placeholderNoModel": "请先配置 AI 模型...",
    "chat.placeholderReady":
      "发送消息给 {model}（Enter 发送，Shift+Enter 换行）",
    "chat.quickSummarize": "总结",
    "chat.quickTranslate": "翻译",
    "chat.quickExplain": "解释",
    "chat.quickCode": "写代码",
    "chat.quickOptimize": "优化",
    "chat.quickSummarizePrompt": "请帮我总结一下：",
    "chat.quickTranslatePrompt": "请翻译成中文：",
    "chat.quickExplainPrompt": "请解释：",
    "chat.quickCodePrompt": "请帮我写代码：",
    "chat.quickOptimizePrompt": "请优化以下内容：",
    "chat.clearInput": "清空",
    "chat.copy": "复制",
    "chat.copied": "已复制",
    "chat.minutesAgo": "{n}分钟前",
    "chat.hoursAgo": "{n}小时前",
    "chat.daysAgo": "{n}天前",
    "chat.showOutput": "显示输出",
    "chat.hideOutput": "隐藏输出",
    "chat.expandOutput": "展开面板",
    "chat.collapseOutput": "收起面板",
    "chat.skillBtn": "技能",
    "chat.selectSkill": "选择技能",
    "chat.skillSelectorTitle": "选择技能",
    "chat.addSkill": "添加技能",
    "chat.skillNamePlaceholder": "技能名称",
    "chat.skillPromptPlaceholder": "输入提示词...",
    "chat.saveSkill": "保存",
    "chat.deleteSkill": "删除",
    "chat.clearSkill": "清除技能",
    "chat.applySkillPrompt": "应用到输入框",
    "chat.goToSkillsPage": "去技能界面添加",
    "chat.goToModelsPage": "去模型界面添加",
    "chat.noSkillsAvailable": "暂无可用技能",
    "chat.justNow": "刚刚",
    "chat.msgCount": "条消息",
    "chat.welcomeTitle": "欢迎使用 WeClaw",
    "chat.welcomeContent":
      "欢迎使用 WeClaw！我是您的AI助手，随时为您提供帮助。\n\n您可以问我任何问题，我会尽力为您解答。如需代码帮助，我可以为您提供各种编程语言的代码示例。",
    "chat.welcomeModelName": "欢迎助手",
    "chat.recoveryTitle": "恢复对话",
    "chat.recoveryContent":
      "⚠️ 加载本地对话数据时出现问题。已为您创建一个新的对话。\n\n您的对话历史可能未能加载。",
    "chat.recoveryModelName": "系统恢复",
    "chat.newConvTitle": "新对话",
    "chat.unknownModel": "未知模型",
    "chat.noResponse": "无响应内容",
    "chat.expandSidebar": "展开侧边栏",
    "chat.collapseSidebar": "收起侧边栏",
    "chat.uploadFileDoing": "正在上传文件...",
    "chat.uploadFileSuccess": "文件上传成功",
    "chat.uploadFileFailed": "文件上传失败，已以文本形式发送",
    "chat.deepseekUploadError": "DeepSeek 文件上传失败，请重试或检查 API 设置",
    // Chat 输出面板（代码计划 / Todo / 文件）
    "chat.panel.codeplan": "代码计划",
    "chat.panel.todo": "待办清单",
    "chat.panel.output": "文件",
    "chat.panel.files": "全部文件",
    "chat.panel.close": "关闭面板",
    "chat.panel.noContent": "暂无内容",
    "chat.panel.viewPlan": "查看计划",
    "chat.panel.viewTodo": "查看待办",
    "chat.panel.viewFiles": "查看文件",
    "chat.plan.title": "代码计划",
    "chat.plan.step": "步骤",
    "chat.plan.steps": "步骤",
    "chat.plan.pending": "待开始",
    "chat.plan.in_progress": "进行中",
    "chat.plan.done": "已完成",
    "chat.plan.skipped": "已跳过",
    "chat.plan.markDone": "标记完成",
    "chat.plan.markPending": "取消完成",
    "chat.plan.setInProgress": "设为进行中",
    "chat.plan.relatedFiles": "关联文件",
    "chat.plan.copyAll": "复制全部步骤",
    "chat.plan.copied": "已复制",
    "chat.plan.progressLabel": "进度",
    "chat.todo.title": "待办清单",
    "chat.todo.addItem": "添加待办",
    "chat.todo.placeholder": "输入待办内容...",
    "chat.todo.priority.low": "低",
    "chat.todo.priority.medium": "中",
    "chat.todo.priority.high": "高",
    "chat.todo.copyAll": "复制全部",
    "chat.todo.copied": "已复制",
    "chat.todo.clearDone": "清除已完成",
    "chat.todo.empty": "暂无待办事项",
    "chat.todo.progress": "完成进度",
    "chat.file.title": "输出文件",
    "chat.file.copy": "复制",
    "chat.file.copied": "已复制",
    "chat.file.download": "下载",
    "chat.file.noFile": "暂无文件",
    "chat.file.lines": "行",
    "chat.file.chars": "字符",
    "chat.file.preview": "预览",
    "chat.file.source": "源码",
    "chat.file.wrap": "自动换行",
    "chat.file.noWrap": "关闭换行",
    "chat.file.expandAll": "展开",
    "chat.file.collapseAll": "收起",
    "chat.file.files": "文件",
    "chat.file.message": "消息",
    "chat.file.selectFile": "选择一个文件查看",
    "chat.file.fileHint": "对话中产生的代码块将自动出现在这里",
    // Claw
    "claw.empty.title": "告诉 Claw 你想做什么",
    "claw.empty.desc": "输入一个目标，Claw 会自动拆解步骤并逐一执行",
    "claw.inputPlaceholder": "输入你想完成的目标...按 Ctrl+Enter 提交",
    "claw.inputPlaceholderActive": "在当前会话中执行新目标... Ctrl+Enter 提交",
    "claw.run": "开始执行",
    "claw.deleteConfirm": "确定要删除这个任务吗？",
    "claw.retry": "重试",
    "claw.stop": "停止",
    "claw.newTask": "新建",
    "claw.taskList": "任务列表",
    "claw.noTasks": "暂无任务",
    "claw.noModels": "暂无模型",
    "claw.selectFile": "选择文件查看",
    "claw.filesCount": "{count} 文件",
    "claw.sessionFiles": "会话文件",
    "claw.openSessionFolder": "打开会话目录",
    "claw.copy": "复制",
    "claw.copied": "已复制",
    "claw.download": "下载",
    "claw.downloadMd": "下载为 .md 文件",
    "claw.copyContent": "复制内容",
    "claw.copyCode": "复制代码",
    "claw.copyFullText": "复制全文",
    "claw.openFolder": "打开文件",
    "claw.context": "+ 上下文",
    "claw.contextPlaceholder": "添加背景信息或上下文（可选）...",
    "claw.clearWorkspace": "清除自定义目录",
    "claw.resizeInput": "拖拽调整输入框高度，双击重置",
    "claw.finalResult": "最终结果",
    "claw.taskFailed": "任务执行失败",
    "claw.planning": "正在规划任务步骤",
    "claw.aiAnalyzing": "AI 正在分析目标并制定执行计划",
    "claw.autoActions": "自动化动作",
    "claw.tokensUsed": "消耗 {count} tokens",
    "claw.ctrlEnter": "Ctrl+Enter 执行",
    // Terminal
    "terminal.toggle": "终端",
    "terminal.title": "终端",
    "terminal.clear": "清空",
    "terminal.expand": "展开终端",
    "terminal.collapse": "收起",
    "terminal.shrink": "收起",
    "terminal.running": "执行中...",
    "terminal.placeholder": "输入命令，按 Enter 执行...",
    "terminal.ready": "输入命令开始执行...",
    "terminal.emptyOutput": "(无输出)",
    "terminal.lines": "行",
    "claw.status.idle": "待执行",
    "claw.status.planning": "规划中",
    "claw.status.running": "执行中",
    "claw.status.paused": "已暂停",
    "claw.status.done": "已完成",
    "claw.status.failed": "失败",
    "claw.status.cancelled": "已取消"
  },
  "en-US": {
    // General
    "app.name": "WeClaw",
    "nav.claw": "Claw",
    "nav.clawAgent": "Claw",
    "nav.dashboard": "Dashboard",
    "nav.chat": "Chat",
    "nav.workflow": "Workflow",
    "nav.tasks": "Tasks",
    "nav.skills": "Skills",
    "nav.tools": "Tools",
    "nav.models": "Models",
    "nav.workspace": "Workspace",
    "nav.history": "History",
    "nav.settings": "Settings",
    // Claw Agent
    "clawAgent.newTaskTitle": "New Task",
    "clawAgent.deleteConfirm": "Are you sure you want to delete this task?",
    "clawAgent.tasks": "Tasks",
    "clawAgent.taskList": "Task List",
    "clawAgent.noTasks": "No tasks yet",
    "clawAgent.newTask": "New Task",
    "clawAgent.retry": "Retry",
    "clawAgent.delete": "Delete",
    "clawAgent.completed": "Completed",
    "clawAgent.steps": "steps",
    "clawAgent.planMode": "Plan Mode",
    "clawAgent.plan": "Plan",
    "clawAgent.placeholderNoTask": "Please create a task first",
    "clawAgent.placeholder": "Describe the task you want to complete...",
    "clawAgent.noTaskSelected": "Please select a task or create a new one",
    "clawAgent.planning": "Analyzing task and creating plan...",
    "clawAgent.waitingForInput": "Describe the task you want to complete",
    "clawAgent.goal": "Goal",
    "clawAgent.error": "Error",
    "clawAgent.output": "Output",
    "clawAgent.finalResult": "Final Result",
    "clawAgent.executing": "Executing...",
    "clawAgent.openFolder": "Open Folder",
    "clawAgent.pause": "Pause",
    "clawAgent.sessionTokens": "Session",
    "clawAgent.totalTokens": "Total",
    "clawAgent.status.planning": "Planning",
    "clawAgent.status.idle": "Idle",
    "clawAgent.status.running": "Running",
    "clawAgent.status.paused": "Paused",
    "clawAgent.status.done": "Done",
    "clawAgent.status.failed": "Failed",
    "clawAgent.status.cancelled": "Cancelled",
    "clawAgent.prompt.analyze": "Analyze this task and create an execution plan",
    "clawAgent.prompt.search": "Search for relevant information",
    "clawAgent.prompt.createFile": "Create a file",
    "clawAgent.prompt.runCode": "Execute some code",
    "clawAgent.prompt.summarize": "Summarize current results",
    "sidebar.expand": "Expand sidebar",
    "sidebar.collapse": "Collapse sidebar",
    // Login
    "login.title": "Login",
    "login.username": "Username",
    "login.usernamePlaceholder": "Enter username",
    "login.password": "Password",
    "login.passwordPlaceholder": "Enter password",
    "login.confirmPassword": "Confirm Password",
    "login.confirmPasswordPlaceholder": "Re-enter password",
    "login.submit": "Login",
    "login.errorEmpty": "Please enter username and password",
    "login.errorMismatch": "Passwords do not match",
    "login.errorShort": "Password must be at least 4 characters",
    "login.errorExists": "Username already exists",
    "login.errorFailed": "Incorrect username or password",
    "login.switchRegister": "No account? Click to register",
    "login.defaultHint": "Default account: admin / admin123",
    "register.title": "Register New Account",
    "register.submit": "Register",
    "register.switchLogin": "Have an account? Click to login",
    // Sidebar user menu
    "sidebar.userMenu.history": "History",
    "sidebar.userMenu.models": "Model Config",
    "sidebar.userMenu.tools": "Tool Manager",
    "sidebar.userMenu.settings": "Settings",
    "sidebar.userMenu.logout": "Logout",
    "sidebar.userMenu.changePassword": "Change Password",
    // Account
    "settings.account": "Account & Security",
    "settings.accountHint": "Current logged in account",
    "settings.oldPassword": "Current Password",
    "settings.oldPasswordPlaceholder": "Enter current password",
    "settings.newPassword": "New Password",
    "settings.newPasswordPlaceholder": "Enter new password",
    "settings.confirmPassword": "Confirm Password",
    "settings.confirmPasswordPlaceholder": "Re-enter new password",
    "settings.changePassword": "Change Password",
    "settings.passwordErrorEmpty": "Please fill in all password fields",
    "settings.passwordErrorMismatch": "New passwords do not match",
    "settings.passwordErrorShort": "New password must be at least 4 characters",
    "settings.passwordErrorWrong": "Current password is incorrect",
    "settings.passwordSuccess": "Password changed successfully",
    // Settings
    "settings.title": "Settings",
    "settings.subtitle": "Manage application settings and preferences",
    "settings.app": "Application Settings",
    "settings.autoStart": "Launch at startup",
    "settings.notifications": "Show notifications",
    "settings.language": "Language",
    "settings.theme": "Theme",
    "settings.theme.light": "Light",
    "settings.theme.dark": "Dark",
    "settings.theme.system": "System",
    "settings.historyDays": "History retention (days)",
    "settings.maxEntries": "Max history entries",
    "settings.tokenLimit": "Token Limit (Daily)",
    "settings.data": "Data Management",
    "settings.security": "Security",
    "settings.advanced": "Advanced",
    "settings.about": "About",
    "settings.export": "Export History",
    "settings.exporting": "Exporting...",
    "settings.clearHistory": "Clear History",
    "settings.clearing": "Clearing...",
    "settings.clearCache": "Clear Cache",
    "settings.reset": "Reset All Settings",
    "settings.devtools": "Open DevTools",
    "settings.managePerms": "Manage Permissions →",
    "settings.resetConfirm":
      "Reset all settings to defaults? This cannot be undone.",
    "settings.resetDone": "Settings have been reset to defaults.",
    "settings.clearConfirm":
      "Clear all history records? This cannot be undone.",
    "settings.clearDone": "History cleared.",
    "settings.clearCacheConfirm":
      "Clear cache? This removes temporary files but won't affect your data.",
    "settings.clearCacheDone": "Cache cleared.",
    "settings.exportDone":
      "History exported successfully! File saved to downloads.",
    "settings.exportFail": "Export failed, please try again.",
    "settings.clearFail": "Clear failed, please try again.",
    // Dashboard
    "dashboard.title": "Dashboard",
    "dashboard.subtitle":
      "Welcome to WeClaw Client. Here is your project overview.",
    "dashboard.workflow": "Workflow Overview",
    "dashboard.tasks": "Task Overview",
    "dashboard.chat": "Chat Data",
    "dashboard.history": "Operation Log",
    "dashboard.noWorkflow": "No workflows. Go to Workflow page to create one.",
    "dashboard.noTask": "No tasks",
    "dashboard.noHistory": "No operation records",
    "dashboard.noChat": "No conversations",
    "dashboard.skills": "Skills Overview",
    "dashboard.tools": "Tools Overview",
    "dashboard.claw": "Claw Overview",
    "dashboard.noClaw": "No Claw tasks yet",
    "dashboard.claw.running": "Running",
    "dashboard.claw.planning": "Planning",
    "dashboard.claw.steps": "steps",
    "dashboard.justNow": "just now",
    "dashboard.minutesAgo": "m ago",
    "dashboard.hoursAgo": "h ago",
    "dashboard.daysAgo": "d ago",
    "dashboard.noSkills": "No skills",
    "dashboard.noTools": "No tools",
    "dashboard.skills.categories": "Categories",
    "dashboard.skills.builtin": "Built-in",
    "dashboard.skills.used": "uses",
    "dashboard.tools.readWrite": "Read-Write",
    "dashboard.tools.disabled": "Disabled",
    "dashboard.tools.securityHint":
      "Some tools have read-write permission. Please confirm you understand the risks.",
    "dashboard.total": "Total",
    "dashboard.enabled": "Enabled",
    "dashboard.disabled": "Disabled",
    "dashboard.lastRun": "Last Run",
    "dashboard.trigger.manual": "Manual",
    "dashboard.trigger.scheduled": "Scheduled",
    "dashboard.trigger.file_change": "File Change",
    "dashboard.trigger.api_call": "API Call",
    "dashboard.status.success": "Success",
    "dashboard.status.failed": "Failed",
    "dashboard.tokenUsage": "Token Usage",
    "dashboard.today": "Today",
    "dashboard.totalTokens": "Total Consumed",
    "dashboard.used": "Used",
    "dashboard.remaining": "Remaining",
    "dashboard.status.running": "Running",
    "dashboard.status.pending": "Pending",
    "dashboard.status.in_progress": "In Progress",
    "dashboard.status.completed": "Completed",
    "dashboard.status.cancelled": "Cancelled",
    "dashboard.priority.low": "Low",
    "dashboard.priority.medium": "Medium",
    "dashboard.priority.high": "High",
    "dashboard.priority.critical": "Critical",
    "dashboard.op.chat_message": "Chat Message",
    "dashboard.op.model_switch": "Model Switch",
    "dashboard.op.workspace_add": "Workspace Add",
    "dashboard.op.file_read": "File Read",
    "dashboard.op.file_write": "File Write",
    "dashboard.op.code_run": "Code Run",
    "dashboard.time.justNow": "just now",
    "dashboard.time.minutesAgo": "minutes ago",
    "dashboard.time.hoursAgo": "hours ago",
    "dashboard.time.daysAgo": "days ago",
    // Workflow
    "workflow.title": "Workflow Automation",
    "workflow.subtitle": "Create and manage automated workflows",
    "workflow.create": "Create Workflow",
    "workflow.noSteps": "No steps yet. Add workflow steps.",
    "workflow.stepsPreview": "Workflow Steps Preview",
    "workflow.outputTitle": "Execution Output",
    "workflow.outputSubtitle": "View workflow execution history and output",
    "workflow.total": "Total Workflows",
    "workflow.enabled": "Enabled",
    "workflow.scheduled": "Scheduled",
    "workflow.successRate": "Success Rate",
    "workflow.newTitle": "New Workflow",
    "workflow.nameLabel": "Workflow Name *",
    "workflow.createBtn": "New Workflow",
    "workflow.createFormTitle": "Create Workflow",
    "workflow.nameLabel2": "Workflow Name *",
    "workflow.namePlaceholder": "e.g.: Code Review Automation",
    "workflow.triggerLabel": "Trigger",
    "workflow.trigger.manual": "Manual",
    "workflow.trigger.scheduled": "Scheduled (Cron)",
    "workflow.trigger.file_change": "File Change",
    "workflow.trigger.api_call": "API Call",
    "workflow.cronConfigLabel": "Cron Schedule Config",
    "workflow.descLabel": "Description",
    "workflow.descPlaceholder":
      "Describe the workflow purpose and functionality",
    "workflow.stepsLabel": "Workflow Steps",
    "workflow.addStep": "Add Step",
    "workflow.enabledLabel": "Enable Workflow",
    "workflow.cancel": "Cancel",
    "workflow.saveCreate": "Create Workflow",
    "workflow.empty": "No workflows",
    "workflow.tagEnabled": "Enabled",
    "workflow.tagDisabled": "Disabled",
    "workflow.status.success": "Success",
    "workflow.status.failed": "Failed",
    "workflow.status.running": "Running",
    "workflow.stepsCount": "{n} steps",
    "workflow.lastRun": "Last Run",
    "workflow.triggerInfo.scheduled": "Scheduled",
    "workflow.triggerInfo.manual": "Manual",
    "workflow.triggerInfo.file_change": "File Change",
    "workflow.runningBtn": "Running",
    "workflow.runNow": "Run Now",
    "workflow.viewOutput": "View Output",
    "workflow.disableBtn": "Disable",
    "workflow.enableBtn": "Enable",
    "workflow.deleteTitle": "Delete Workflow",
    "workflow.deleteConfirm": "Are you sure you want to delete this workflow?",
    "workflow.requiredName": "Please enter a workflow name",
    "workflow.stepPrefix": "Step",
    "workflow.stepDefaultName": "New Step",
    "workflow.stepDefaultDesc": "Describe the step functionality",
    "workflow.editStep": "Edit Step",
    // CronConfig labels
    "workflow.cron.minute": "Minute",
    "workflow.cron.hour": "Hour",
    "workflow.cron.day": "Day",
    "workflow.cron.month": "Month",
    "workflow.cron.week": "Weekday",
    "workflow.cron.exprLabel": "Cron Expression:",
    "workflow.cron.examplesLabel": "Examples:",
    "workflow.cron.example1": "Weekdays at 9:00",
    "workflow.cron.example2": "Every 2 hours",
    // OutputViewer labels
    "workflow.output.title": "Execution Output",
    "workflow.output.lastRunTime": "Last Run Time",
    "workflow.output.runStatus": "Run Status",
    "workflow.output.stepsCount": "Steps Count",
    "workflow.output.output": "Output",
    "workflow.output.steps": "Execution Steps",
    "workflow.output.stepStatus": "Status: Completed",
    "workflow.output.noRecord": "No execution records",
    // Workflow new keys
    "workflow.trigger.webhook": "Webhook",
    "workflow.triggerInfo.webhook": "Webhook",
    "workflow.triggerInfo.api_call": "API Call",
    "workflow.editBtn": "Edit Workflow",
    "workflow.saveBtn": "Save",
    "workflow.backList": "Back to List",
    "workflow.nodeLibrary": "Node Library",
    "workflow.fitView": "Fit View",
    "workflow.canvasEmpty": "Canvas is empty",
    "workflow.canvasEmptyHint":
      "Drag nodes from the left panel, or connect them with edges",
    "workflow.node.label": "Node Name",
    "workflow.node.description": "Description",
    "workflow.node.save": "Save Node",
    "workflow.node.delete": "Delete Node",
    "workflow.node.deleteConfirm": "Are you sure you want to delete this node?",
    "workflow.node.startTip":
      "The start node is the entry point. No configuration needed.",
    "workflow.node.model": "Model",
    "workflow.node.prompt": "Prompt",
    "workflow.node.temperature": "Temperature",
    "workflow.node.outputVar": "Output Variable",
    "workflow.node.condition": "Condition Expression",
    "workflow.node.conditionTip":
      "Use {{variable}} to reference context variables, e.g. {{score}} > 80",
    "workflow.node.operation": "Operation",
    "workflow.node.filePath": "File Path",
    "workflow.node.fileContent": "File Content",
    "workflow.node.language": "Language",
    "workflow.node.code": "Code",
    "workflow.node.taskTitle": "Task Title",
    "workflow.node.taskDesc": "Task Description",
    "workflow.node.priority": "Priority",
    "workflow.node.channel": "Channel",
    "workflow.node.message": "Message",
    "workflow.node.recipients": "Recipients",
    "workflow.node.url": "Target URL",
    "workflow.node.selector": "CSS Selector",
    "workflow.node.dataOp": "Data Operation",
    "workflow.node.inputVar": "Input Variable",
    "workflow.node.script": "Script",
    "workflow.node.command": "Command",
    "workflow.node.workingDir": "Working Directory",
    "workflow.node.timeout": "Timeout (sec)",
    "workflow.node.skillId": "Skill ID",
    "workflow.node.inputs": "Input Params (JSON)",
    "workflow.node.branches": "Branch Count",
    "workflow.node.waitStrategy": "Wait Strategy",
    "workflow.node.iterateVar": "Iterate Variable",
    "workflow.node.itemVar": "Item Variable Name",
    "workflow.node.maxIterations": "Max Iterations",
    "workflow.node.endMessage": "End Message",
    "workflow.node.selectTool": "Select Tool",
    "workflow.node.toolParams": "Tool Parameters",
    "workflow.node.toolNoParams": "This tool requires no parameters",
    "workflow.node.noEnabledTools":
      "No enabled tools found. Please enable tools in Tool Management first.",
    "workflow.node.toolUncategorized": "Uncategorized",
    "workflow.moreSettings": "More Settings",
    "workflow.collapseSettings": "Collapse Settings",
    "workflow.expandSettings": "Expand Settings",
    // Tasks
    "tasks.title": "Task Management",
    "tasks.subtitle": "Manage your project tasks and workflows",
    "tasks.create": "New Task",
    "tasks.statusAll": "All Status",
    "tasks.priorityAll": "All Priority",
    "tasks.status": "Status",
    "tasks.priority": "Priority",
    "tasks.titlePlaceholder": "Enter task title",
    "tasks.noTasks": "No tasks",
    "tasks.responsible": "Responsible",
    "tasks.allResponsible": "All Responsible",
    "tasks.systemAdmin": "System Administrator",
    "tasks.currentUser": "Current User",
    "tasks.totalTasks": "Total {count} tasks",
    "tasks.createNew": "Create New Task",
    "tasks.taskTitle": "Task Title *",
    "tasks.taskDesc": "Task Description",
    "tasks.estimatedHours": "Estimated Hours",
    "tasks.dueDate": "Due Date",
    "tasks.tags": "Tags (comma separated)",
    "tasks.exampleTags": "e.g.: frontend, bug, feature",
    "tasks.cancel": "Cancel",
    "tasks.createBtn": "Create Task",
    "tasks.expandDesc": "Task Description",
    "tasks.details": "Task Details",
    "tasks.creator": "Created by:",
    "tasks.assignee": "Assignee:",
    "tasks.deadline": "Due:",
    "tasks.estimatedTime": "Estimated:",
    "tasks.actualTime": "Actual:",
    "tasks.hours": "hours",
    "tasks.tagsNotes": "Tags & Notes",
    "tasks.dependency": "Dependencies",
    "tasks.dependencyCount": "Depends on {count} other tasks",
    "tasks.markComplete": "Mark Complete",
    "tasks.edit": "Edit",
    "tasks.delete": "Delete",
    "tasks.deleteConfirm": "Are you sure you want to delete this task?",
    "tasks.stats": "Task Statistics",
    "tasks.totalCount": "Total Tasks",
    "tasks.inProgress": "In Progress",
    "tasks.completed": "Completed",
    "tasks.pending": "Pending",
    // Skills
    "skills.title": "Skill Library",
    "skills.subtitle":
      "Manage skills available to the AI assistant. Create, edit, import and share.",
    "skills.importExport": "Import / Export",
    "skills.newSkill": "New Skill",
    "skills.allSkills": "All Skills",
    "skills.enabled": "Enabled",
    "skills.custom": "Custom",
    "skills.searchPlaceholder": "Search by name, description or tags...",
    "skills.categoryAll": "All",
    "skills.cat.productivity": "Productivity",
    "skills.cat.coding": "Coding",
    "skills.cat.writing": "Writing",
    "skills.cat.analysis": "Analysis",
    "skills.cat.communication": "Communication",
    "skills.cat.custom": "Custom",
    "skills.notFound": 'No skills found for "{q}"',
    "skills.emptyCategory": "No skills in this category",
    "skills.builtin": "Built-in",
    "skills.unnamed": "Unnamed Skill",
    "skills.noDesc": "No description",
    "skills.usageCount": "uses",
    "skills.usedToast": "Applied skill: ",
    "skills.btnUse": "Use Skill",
    "skills.btnEdit": "Edit",
    "skills.btnExport": "Export",
    "skills.btnDelete": "Delete",
    "skills.toggleEnable": "Click to disable",
    "skills.toggleDisable": "Click to enable",
    "skills.deleteConfirm": "Delete this skill? This action cannot be undone.",
    "skills.editor.titleEdit": "Edit Skill",
    "skills.editor.titleNew": "New Skill",
    "skills.editor.tabBasic": "Basic Info",
    "skills.editor.tabContent": "Skill Content",
    "skills.editor.name": "Skill Name",
    "skills.editor.namePlaceholder": "e.g. Generate Weekly Report",
    "skills.editor.nameRequired": "Skill name is required",
    "skills.editor.desc": "Description",
    "skills.editor.descPlaceholder": "Brief description of the skill",
    "skills.editor.category": "Category",
    "skills.editor.version": "Version",
    "skills.editor.author": "Author",
    "skills.editor.authorPlaceholder": "Author name",
    "skills.editor.sourceUrl": "Source URL (optional)",
    "skills.editor.tags": "Tags",
    "skills.editor.tagsPlaceholder": "Type a tag and press Enter",
    "skills.editor.content": "Skill Content (Prompt / Instructions)",
    "skills.editor.contentHint":
      "Define the AI behavior when this skill is applied. Markdown supported.",
    "skills.editor.contentPlaceholder":
      "Describe the detailed prompt or instructions for this skill...",
    "skills.editor.contentRequired": "Skill content is required",
    "skills.editor.chars": "chars",
    "skills.editor.cancel": "Cancel",
    "skills.editor.saveEdit": "Save Changes",
    "skills.editor.saveNew": "Create Skill",
    "skills.ie.title": "Import / Export Skills",
    "skills.ie.exportTitle": "Export Skill Package",
    "skills.ie.exportDesc":
      "Export all custom skills ({n}) as a JSON file to share with others.",
    "skills.ie.exportBtn": "Export All Custom Skills",
    "skills.ie.importFileTitle": "Import from Local File",
    "skills.ie.importFileBtn": "Select Skill Package (.json)",
    "skills.ie.importUrlTitle": "Import from URL (Community Share)",
    "skills.ie.importUrlBtn": "Import",
    "skills.ie.importing": "Fetching...",
    "skills.ie.fetchFail": "Fetch failed: ",
    "skills.ie.invalidFormat":
      "Invalid file format. Please check the skill package JSON.",
    "skills.ie.noImportable":
      "No importable skills found (built-in skills are skipped).",
    "skills.ie.importSuccess": "Import successful",
    "skills.ie.importCount": ", {n} skills imported",
    "skills.ie.close": "Close",
    // Tools
    "tools.title": "Tool Management",
    "tools.subtitle":
      "Manage tools available to the AI. Configure permissions and custom integrations.",
    "tools.newTool": "New Tool",
    "tools.allTools": "All Tools",
    "tools.available": "Available",
    "tools.readOnly": "Read-Only",
    "tools.disabled": "Disabled",
    "tools.searchPlaceholder": "Search by name, description or group...",
    "tools.typeAll": "All",
    "tools.type.builtin": "Built-in",
    "tools.type.script": "Script",
    "tools.type.api": "API",
    "tools.perm.read_only": "Read-Only",
    "tools.perm.read_write": "Read-Write",
    "tools.perm.disabled": "Disabled",
    "tools.notFound": 'No tools found for "{q}"',
    "tools.emptyType": "No tools of this type",
    "tools.builtin": "Built-in",
    "tools.unnamed": "Unnamed Tool",
    "tools.noDesc": "No description",
    "tools.paramCount": "params",
    "tools.callCount": "calls:",
    "tools.callCountUnit": "",
    "tools.permLabel": "Permission guide: ",
    "tools.permReadOnlyDesc": "Can read data only, no modifications",
    "tools.permReadWriteDesc": "Can read and write data",
    "tools.permDisabledDesc": "AI cannot call this tool",
    "tools.toggleEnable": "Click to disable",
    "tools.toggleDisable": "Click to enable",
    "tools.btnEdit": "Edit",
    "tools.btnDelete": "Delete",
    "tools.deleteConfirm": "Delete this tool? This action cannot be undone.",
    "tools.warnTitle": " tool(s) have Read-Write permission",
    "tools.warnDesc":
      "Read-write tools can modify the file system or external services. Only authorize trusted tools.",
    "tools.warnSetReadOnly": "Set All to Read-Only",
    "tools.editor.titleEdit": "Edit Tool",
    "tools.editor.titleNew": "New Tool",
    "tools.editor.tabBasic": "Basic Info",
    "tools.editor.tabParams": "Parameters",
    "tools.editor.tabApi": "API Config",
    "tools.editor.tabScript": "Script",
    "tools.editor.icon": "Icon",
    "tools.editor.name": "Tool Name",
    "tools.editor.namePlaceholder": "e.g. HTTP Request",
    "tools.editor.nameRequired": "Tool name is required",
    "tools.editor.type": "Tool Type",
    "tools.editor.desc": "Description",
    "tools.editor.descPlaceholder": "Describe the tool's function and use case",
    "tools.editor.category": "Group",
    "tools.editor.categoryPlaceholder": "e.g. File System",
    "tools.editor.permission": "Default Permission",
    "tools.editor.paramsHint":
      "Define the parameters required when calling this tool",
    "tools.editor.addParam": "Add Parameter",
    "tools.editor.noParams":
      'No parameters defined. Click "Add Parameter" to start.',
    "tools.editor.paramNum": "Param #",
    "tools.editor.paramName": "Name",
    "tools.editor.paramType": "Type",
    "tools.editor.paramDesc": "Description",
    "tools.editor.paramDescPlaceholder": "Parameter description",
    "tools.editor.paramRequired": "Required",
    "tools.editor.paramDefault": "Default value (optional)",
    "tools.editor.apiEndpoint": "API Endpoint",
    "tools.editor.apiEndpointRequired": "API endpoint is required",
    "tools.editor.apiMethod": "HTTP Method",
    "tools.editor.apiHeaders": "Headers (JSON, optional)",
    "tools.editor.scriptContent": "Script Content",
    "tools.editor.scriptContentRequired": "Script content is required",
    "tools.editor.scriptHint":
      "Supports Shell / Python / Node.js. Parameters are passed as environment variables.",
    "tools.editor.cancel": "Cancel",
    "tools.editor.saveEdit": "Save Changes",
    "tools.editor.saveNew": "Create Tool",
    // History
    "history.title": "Operation History",
    "history.subtitle": "View detailed operation records and security logs",
    "history.refresh": "Refresh",
    "history.syncBtn": "Scheduled Sync",
    "history.syncEnabled": "Scheduled Sync Enabled",
    "history.syncFailed": "Sync Failed",
    "history.syncNow": "Sync Now",
    "history.syncConfig": "Sync Configuration",
    "history.noRecords": "No operation records",
    // ModelConfig
    "models.title": "Model Config",
    "models.subtitle": "Configure and manage your AI model API connections",
    "models.add": "Add Model",
    "models.addNew": "Add New Model",
    "models.nameLabel": "Model Name *",
    "models.typeLabel": "Model Type *",
    "models.endpointLabel": "API Endpoint *",
    "models.keyLabel": "API Key",
    "models.setDefault": "Set as Default",
    "models.namePlaceholder": "e.g.: GPT-4",
    "models.endpointPlaceholder":
      "e.g.: https://api.openai.com/v1/chat/completions",
    "models.keyPlaceholder": "Enter API Key",
    "models.keyEditPlaceholder": "Fill in to update the key",
    "models.cancel": "Cancel",
    "models.createBtn": "Create Model",
    "models.editTitle": "Edit Model",
    "models.editNameLabel": "Model Name *",
    "models.editTypeLabel": "Model Type *",
    "models.editEndpointLabel": "API Endpoint *",
    "models.editKeyLabel": "API Key",
    "models.editSetDefault": "Set as Default",
    "models.saveBtn": "Save Changes",
    "models.listTitle": "Configured Models",
    "models.empty": 'No models configured. Click "Add Model" to get started.',
    "models.tagDefault": "Default",
    "models.tagCurrent": "In Use",
    "models.titleSetDefault": "Set as Default",
    "models.titleEdit": "Edit",
    "models.titleDelete": "Delete",
    "models.titleUse": "Use Now",
    "models.deleteConfirm":
      "Are you sure you want to delete this model configuration?",
    "models.deleteSuccess": "Model configuration deleted.",
    "models.deleteFail": "Delete failed, please try again.",
    "models.deleteError": "Delete failed, please check the console.",
    "models.saveRequired": "Please fill in model name and API endpoint.",
    "models.saveSuccess": "Model configuration saved.",
    "models.saveFail": "Save failed, please try again.",
    "models.createSuccess": "Model configuration created.",
    "models.createFail": "Create failed, please try again.",
    "models.setDefaultSuccess": "Set as default model.",
    "models.type.custom": "Custom API",
    // Workspace
    "workspace.title": "Workspace Manager",
    "workspace.subtitle":
      "Set up and manage secure workspaces with permission control",
    "workspace.current": "Current Workspace",
    "workspace.setTitle": "Workspace Configured",
    "workspace.setDesc":
      "All operations are restricted to this directory. Out-of-scope operations will be logged.",
    "workspace.name": "Workspace Name",
    "workspace.path": "Path",
    "workspace.createdAt": "Created At",
    "workspace.status": "Status",
    "workspace.active": "Active",
    "workspace.change": "Change Workspace",
    "workspace.clear": "Clear Workspace",
    "workspace.noSet": "Workspace Not Set",
    "workspace.noSetDesc":
      "Please configure a workspace to enable permission control.",
    "workspace.setBtn": "Set Workspace",
    "workspace.testTool": "Permission Test Tool",
    "workspace.testPath": "Test Path",
    "workspace.testing": "Testing...",
    "workspace.testBtn": "Test Permission",
    "workspace.allowed": "Access Allowed",
    "workspace.denied": "Access Denied",
    "workspace.testPathHint":
      "Enter any path to test whether it is within the current workspace (has operation permission).",
    "workspace.testPathPlaceholder": "e.g.: /Users/username/Documents/project",
    "workspace.securityTitle": "Security Notes",
    "workspace.permControl": "Permission Control",
    "workspace.permControlDesc":
      "After setting the workspace, all file operations (read, write, modify) will be restricted to that directory. Attempts to access files outside the workspace will trigger a security warning and be logged.",
    "workspace.opRecord": "Operation Records",
    "workspace.opRecordDesc":
      'All operations (including permission check results) are logged locally. You can view detailed records on the "Operation History" page.',
    "workspace.securityAdvice": "Security Advice",
    "workspace.securityAdviceDesc":
      "1. Set workspace to project-specific directories\n2. Regularly review operation history\n3. Grant only minimum necessary permissions\n4. Use strong passwords to protect API keys",
    "workspace.pathInside": "Path is within workspace",
    "workspace.pathOutside": "Path is outside workspace",
    "workspace.testFailed": "Test failed, please check path format",
    "workspace.clearConfirm":
      "Are you sure you want to clear workspace settings? You need to re-configure to continue operations.",
    "workspace.clearDone": "Workspace cleared. Please re-configure.",
    "workspace.pathMustBe": "The path must be within workspace: ",
    "workspace.inputPath": "Please enter a path to test",
    // History (extra)
    "history.syncBtn2": "Scheduled Sync",
    "history.refreshBtn": "Refresh",
    "history.filterType": "Filter Type",
    "history.filterAll": "All Records",
    "history.filterDenied": "Permission Denied",
    "history.filterSuccess": "Success",
    "history.filterWarning": "Warning",
    "history.filterError": "Error",
    "history.searchLabel": "Search",
    "history.searchPlaceholder": "Search by type, target, or permission check",
    "history.statsLabel": "Statistics",
    "history.totalRecords": "Total",
    "history.successRecords": "Success",
    "history.deniedRecords": "Denied",
    "history.loading": "Loading history...",
    "history.empty": "No history records",
    "history.showCount": "Total {count} records",
    "history.maxCount": "Showing last 200 records only",
    "history.pageInfo": "Page {page} / {total}, {size} per page",
    "history.prevPage": "Previous",
    "history.nextPage": "Next",
    "history.pageSizeLabel": "Per page",
    "history.pageUnit": "",
    "history.opTarget": "Target",
    "history.permCheck": "Permission Check",
    "history.opStatus": "Status",
    "history.details": "Details",
    "history.noDetails": "No details available",
    "history.fullTimestamp": "Full Timestamp",
    "history.infoTitle": "About Operation History",
    "history.infoContent": "What is recorded",
    "history.infoContentDesc":
      "The system records all key operations including: text processing, file access, permission checks, model configuration changes, and workspace changes. Each record includes timestamp, operation type, target, permission check result, and detailed parameters.",
    "history.securityMonitor": "Security Monitoring",
    "history.securityMonitorDesc":
      'Pay attention to "permission denied" records, which indicate attempts to access outside the workspace. Regularly checking these helps identify potential security issues.',
    "history.syncDesc": "Scheduled Sync",
    "history.syncDescContent":
      'Click the "Scheduled Sync" button to configure automatic syncing of operation history to a remote server. Supports interval mode (every N minutes) and Cron expression, with Bearer Token, Basic Auth, and API Key authentication.',
    "history.retentionTitle": "Data Retention",
    "history.retentionDesc":
      "History is stored in a local SQLite database, retaining only the last 200 records to prevent database bloat. To export or back up records, visit the Settings page.",
    "history.syncConfigTitle": "Sync Configuration",
    "history.syncEnabled2": "Scheduled Sync Enabled",
    "history.target": "Target: ",
    "history.notSet": "(not set)",
    "history.lastSync": "Last: ",
    "history.frequency": "Frequency: ",
    "history.syncFailed2": "Sync Failed",
    "history.syncing": "Syncing…",
    "history.syncNow2": "Sync Now",
    "history.basicConfig": "Basic Config",
    "history.enableSync": "Enable Scheduled Sync",
    "history.serverUrl": "Server URL",
    "history.serverUrlPlaceholder": "https://your-server.com/api/history/sync",
    "history.serverUrlHint": "Sends a POST request with JSON data to this URL",
    "history.authType": "Auth Type",
    "history.authNone": "No Auth",
    "history.authBearer": "Bearer Token",
    "history.authBasic": "Basic Auth",
    "history.authApiKey": "API Key (Custom Header)",
    "history.headerName": "Header Name",
    "history.apiKeyValue": "API Key Value",
    "history.username": "Username",
    "history.password": "Password",
    "history.scheduleRules": "Schedule Rules",
    "history.ruleType": "Rule Type",
    "history.intervalMode": "Interval",
    "history.cronMode": "Cron Expression",
    "history.syncInterval": "Sync Interval",
    "history.minutes": "minutes",
    "history.cronPreset.daily0": "Daily 0:00",
    "history.cronPreset.daily8": "Daily 8:00",
    "history.cronHint": "(min hour day month weekday)",
    "history.syncOnStartup": "Sync on Startup",
    "history.syncOnStartupHint": "Trigger a sync when the app starts",
    "history.advancedOptions": "Advanced Options",
    "history.maxSyncRecords": "Max records per sync",
    "history.testSync": "Test Sync Now",
    "history.cancel": "Cancel",
    "history.saveConfig": "Save Config",
    "history.configSaved": "Config saved",
    "history.syncLogs": "Sync Logs (last {count})",
    "history.notEnabled": "Not enabled",
    "history.neverSync": "Never synced",
    "history.everyHours": "Every {n} hour(s)",
    "history.everyMinutes": "Every {n} minute(s)",
    "history.noServerConfig": "Server URL not configured, skipping sync",
    "history.syncSuccessMsg": "Successfully synced {count} records",
    "history.syncFailHttp": "Sync failed: HTTP {status} {statusText}",
    "history.syncException": "Sync error: {msg}",
    "history.opType.text_processing": "Text Processing",
    "history.opType.file_access": "File Access",
    "history.opType.permission_check": "Permission Check",
    "history.opType.model_config": "Model Config",
    "history.opType.workspace_change": "Workspace Change",
    "history.opType.unknown": "Unknown Operation",
    // Settings extra (replacing inline ternaries)
    "settings.dataLocalNote":
      "All data is stored locally to ensure your privacy and security.",
    "settings.securityTitle2": "Security Recommendations",
    "settings.securityItem1":
      "Regularly check permission-denied records in operation history",
    "settings.securityItem2":
      "Ensure workspace settings are correct to avoid accidental operations",
    "settings.securityItem3": "Regularly export important data as backup",
    "settings.securityItem4": "Use strong passwords to protect API keys",
    "settings.appPerms": "App Permissions",
    "settings.appPermsDesc": "View and manage application permissions",
    "settings.resetTitle": "Reset All Settings",
    "settings.resetDesc":
      "Restore all settings to defaults. Your data won't be affected.",
    "settings.devtoolsTitle": "Developer Tools",
    "settings.devtoolsDesc": "Open DevTools for debugging",
    "settings.aboutTitle": "About",
    "settings.versionLabel": "Version",
    "settings.frameworkLabel": "Framework",
    "settings.frontendLabel": "Frontend",
    "settings.aboutDesc":
      "WeClaw Client is a cross-platform AI assistant desktop app with model selection, custom configuration, secure workspace permission control, and full operation history logging for security audits.",
    "settings.copyright": "Privacy Policy · Terms of Service",
    // Chat
    "chat.newConversation": "New Conversation",
    "chat.selectConversation": "Select Conversation",
    "chat.startNew": "Start New Conversation",
    "chat.startChat": "Start Chatting",
    "chat.startChatHint": "Type a message to start chatting with AI",
    "chat.selectOrCreate": "Select or Create Conversation",
    "chat.selectOrCreateHint":
      'Choose a conversation on the left, or click "+" to create a new one',
    "chat.conversationList": "Conversations",
    "chat.searchPlaceholder": "Search conversations...",
    "chat.filterAll": "All",
    "chat.noMatch": "No matching conversations",
    "chat.clearFilter": "Clear filters",
    "chat.noConversation": "No conversations",
    "chat.deleteConversation": "Delete Conversation",
    "chat.deleteConfirm":
      "Are you sure you want to delete this conversation? This cannot be undone.",
    "chat.modelLabel": "Model:",
    "chat.workspaceLabel": "Workspace:",
    "chat.online": "Online",
    "chat.selectModel": "Select a model",
    "chat.uploadImage": "Upload image (paste/drag supported)",
    "chat.uploadFile": "Upload file",
    "chat.imageBtn": "Image",
    "chat.fileBtn": "File",
    "chat.newChatBtn": "New Chat",
    "chat.removeAttachment": "Remove",
    "chat.dropHint": "Drop to attach files",
    "chat.attachmentsCount": "{n} attachment(s)",
    "chat.sendBtn": "Send (Enter)",
    "chat.fileSizeExceeded": 'File "{name}" exceeds 20MB limit, skipped.',
    "chat.placeholderNoModel": "Please configure an AI model first...",
    "chat.placeholderReady":
      "Message {model} (Enter to send, Shift+Enter for newline)",
    "chat.quickSummarize": "Summarize",
    "chat.quickTranslate": "Translate",
    "chat.quickExplain": "Explain",
    "chat.quickCode": "Write Code",
    "chat.quickOptimize": "Optimize",
    "chat.quickSummarizePrompt": "Please summarize: ",
    "chat.quickTranslatePrompt": "Please translate to English: ",
    "chat.quickExplainPrompt": "Please explain: ",
    "chat.quickCodePrompt": "Please write code for: ",
    "chat.quickOptimizePrompt": "Please optimize: ",
    "chat.clearInput": "Clear",
    "chat.copy": "Copy",
    "chat.copied": "Copied",
    "chat.minutesAgo": "{n}m ago",
    "chat.hoursAgo": "{n}h ago",
    "chat.daysAgo": "{n}d ago",
    "chat.showOutput": "Show Output",
    "chat.hideOutput": "Hide Output",
    "chat.expandOutput": "Expand Panel",
    "chat.collapseOutput": "Collapse Panel",
    "chat.skillBtn": "Skill",
    "chat.selectSkill": "Select skill",
    "chat.skillSelectorTitle": "Select Skill",
    "chat.addSkill": "Add skill",
    "chat.skillNamePlaceholder": "Skill name",
    "chat.skillPromptPlaceholder": "Enter prompt...",
    "chat.saveSkill": "Save",
    "chat.deleteSkill": "Delete",
    "chat.clearSkill": "Clear skill",
    "chat.applySkillPrompt": "Apply to input",
    "chat.goToSkillsPage": "Add in Skills page",
    "chat.goToModelsPage": "Add in Models page",
    "chat.noSkillsAvailable": "No skills available",
    "chat.justNow": "just now",
    "chat.msgCount": "messages",
    "chat.welcomeTitle": "Welcome to WeClaw",
    "chat.welcomeContent":
      "Welcome to WeClaw! I am your AI assistant, ready to help you anytime.\n\nYou can ask me anything and I will do my best to help. For coding assistance, I can provide examples in various programming languages.",
    "chat.welcomeModelName": "Welcome Bot",
    "chat.recoveryTitle": "Recovery",
    "chat.recoveryContent":
      "⚠️ An error occurred loading local conversation data. A new conversation has been created.\n\nYour conversation history may not have loaded.",
    "chat.recoveryModelName": "System Recovery",
    "chat.newConvTitle": "New Conversation",
    "chat.unknownModel": "Unknown Model",
    "chat.noResponse": "No response content",
    "chat.expandSidebar": "Expand sidebar",
    "chat.collapseSidebar": "Collapse sidebar",
    "chat.uploadFileDoing": "Uploading files...",
    "chat.uploadFileSuccess": "Files uploaded successfully",
    "chat.uploadFileFailed": "File upload failed, sent as text",
    "chat.deepseekUploadError":
      "DeepSeek file upload failed. Please try again or check API settings.",
    // Chat output panel (CodePlan / Todo / File)
    "chat.panel.codeplan": "Code Plan",
    "chat.panel.todo": "Todo List",
    "chat.panel.output": "File",
    "chat.panel.files": "All Files",
    "chat.panel.close": "Close panel",
    "chat.panel.noContent": "No content yet",
    "chat.panel.viewPlan": "View Plan",
    "chat.panel.viewTodo": "View Todo",
    "chat.panel.viewFiles": "View Files",
    "chat.plan.title": "Code Plan",
    "chat.plan.step": "Step",
    "chat.plan.steps": "steps",
    "chat.plan.pending": "Pending",
    "chat.plan.in_progress": "In Progress",
    "chat.plan.done": "Done",
    "chat.plan.skipped": "Skipped",
    "chat.plan.markDone": "Mark as done",
    "chat.plan.markPending": "Mark as pending",
    "chat.plan.setInProgress": "Set in progress",
    "chat.plan.relatedFiles": "Related files",
    "chat.plan.copyAll": "Copy all steps",
    "chat.plan.copied": "Copied",
    "chat.plan.progressLabel": "Progress",
    "chat.todo.title": "Todo List",
    "chat.todo.addItem": "Add item",
    "chat.todo.placeholder": "Enter todo...",
    "chat.todo.priority.low": "Low",
    "chat.todo.priority.medium": "Medium",
    "chat.todo.priority.high": "High",
    "chat.todo.copyAll": "Copy all",
    "chat.todo.copied": "Copied",
    "chat.todo.clearDone": "Clear done",
    "chat.todo.empty": "No todo items",
    "chat.todo.progress": "Progress",
    "chat.file.title": "Output Files",
    "chat.file.copy": "Copy",
    "chat.file.copied": "Copied",
    "chat.file.download": "Download",
    "chat.file.noFile": "No files",
    "chat.file.lines": "lines",
    "chat.file.chars": "chars",
    "chat.file.preview": "Preview",
    "chat.file.source": "Source",
    "chat.file.wrap": "Word wrap",
    "chat.file.noWrap": "No wrap",
    "chat.file.expandAll": "Expand",
    "chat.file.collapseAll": "Collapse",
    "chat.file.files": "Files",
    "chat.file.message": "Message",
    "chat.file.selectFile": "Select a file to view",
    "chat.file.fileHint":
      "Code blocks generated in the conversation will appear here",
    // Claw
    "claw.empty.title": "Tell Claw what you want to do",
    "claw.empty.desc":
      "Enter a goal, and Claw will break it down into steps and execute them",
    "claw.inputPlaceholder": "Enter your goal... Press Ctrl+Enter to submit",
    "claw.inputPlaceholderActive":
      "Execute new goal in current session... Ctrl+Enter to submit",
    "claw.run": "Start execution",
    "claw.deleteConfirm": "Are you sure you want to delete this task?",
    "claw.retry": "Retry",
    "claw.stop": "Stop",
    "claw.newTask": "New",
    "claw.taskList": "Task List",
    "claw.noTasks": "No tasks",
    "claw.noModels": "No models",
    "claw.selectFile": "Select a file to view",
    "claw.filesCount": "{count} files",
    "claw.sessionFiles": "Session Files",
    "claw.openSessionFolder": "Open session folder",
    "claw.copy": "Copy",
    "claw.copied": "Copied",
    "claw.download": "Download",
    "claw.downloadMd": "Download as .md file",
    "claw.copyContent": "Copy content",
    "claw.copyCode": "Copy code",
    "claw.copyFullText": "Copy full text",
    "claw.openFolder": "Open file",
    "claw.context": "+ Context",
    "claw.contextPlaceholder": "Add background info or context (optional)...",
    "claw.clearWorkspace": "Clear custom directory",
    "claw.resizeInput": "Drag to resize input height, double-click to reset",
    "claw.finalResult": "Final Result",
    "claw.taskFailed": "Task execution failed",
    "claw.planning": "Planning task steps...",
    "claw.aiAnalyzing":
      "AI is analyzing the goal and creating an execution plan",
    "claw.autoActions": "Automated Actions",
    "claw.tokensUsed": "Used {count} tokens",
    "claw.ctrlEnter": "Ctrl+Enter to execute",
    // Terminal
    "terminal.toggle": "Terminal",
    "terminal.title": "Terminal",
    "terminal.clear": "Clear",
    "terminal.expand": "Expand terminal",
    "terminal.collapse": "Collapse",
    "terminal.shrink": "Collapse",
    "terminal.running": "Running...",
    "terminal.placeholder": "Enter command, press Enter...",
    "terminal.ready": "Enter a command to start...",
    "terminal.emptyOutput": "(no output)",
    "terminal.lines": "lines",
    "claw.status.idle": "Idle",
    "claw.status.planning": "Planning",
    "claw.status.running": "Running",
    "claw.status.paused": "Paused",
    "claw.status.done": "Completed",
    "claw.status.failed": "Failed",
    "claw.status.cancelled": "Cancelled"
  }
};

// ─── 工具：应用主题 ────────────────────────────────────────────────────────────
let _systemMediaQuery: MediaQueryList | null = null;
let _systemListener: (() => void) | null = null;

function applyTheme(theme: Theme) {
  const root = document.documentElement;

  // 移除上次 system 监听
  if (_systemMediaQuery && _systemListener) {
    _systemMediaQuery.removeEventListener("change", _systemListener);
    _systemListener = null;
  }

  if (theme === "dark") {
    root.classList.add("dark");
  } else if (theme === "light") {
    root.classList.remove("dark");
  } else {
    // system：跟随系统，并监听变化
    const mq = window.matchMedia("(prefers-color-scheme: dark)");
    _systemMediaQuery = mq;
    const apply = () => root.classList.toggle("dark", mq.matches);
    apply();
    _systemListener = apply;
    mq.addEventListener("change", apply);
  }
}

// ─── Context ───────────────────────────────────────────────────────────────────
const SettingsContext = createContext<SettingsContextValue | null>(null);

export const SettingsProvider: React.FC<{ children: React.ReactNode }> = ({
  children
}) => {
  const [settings, setSettings] = useState<AppSettings>(() => {
    try {
      const raw = localStorage.getItem(SETTINGS_KEY);
      return raw
        ? { ...DEFAULT_SETTINGS, ...JSON.parse(raw) }
        : { ...DEFAULT_SETTINGS };
    } catch {
      return { ...DEFAULT_SETTINGS };
    }
  });

  // 初始化时应用语言和主题
  useEffect(() => {
    document.documentElement.lang = settings.language;
    applyTheme(settings.theme);
  }, []); // eslint-disable-line react-hooks/exhaustive-deps

  const updateSettings = useCallback((patch: Partial<AppSettings>) => {
    setSettings((prev) => {
      const next = { ...prev, ...patch };
      localStorage.setItem(SETTINGS_KEY, JSON.stringify(next));

      // 实时应用语言
      if (patch.language !== undefined) {
        document.documentElement.lang = patch.language;
      }
      // 实时应用主题
      if (patch.theme !== undefined) {
        applyTheme(patch.theme);
      }

      return next;
    });
  }, []);

  const resetSettings = useCallback(() => {
    setSettings({ ...DEFAULT_SETTINGS });
    localStorage.setItem(SETTINGS_KEY, JSON.stringify(DEFAULT_SETTINGS));
    document.documentElement.lang = DEFAULT_SETTINGS.language;
    applyTheme(DEFAULT_SETTINGS.theme);
  }, []);

  const t = useCallback(
    (key: string, vars?: Record<string, string | number>) => {
      const dict = translations[settings.language] ?? translations["zh-CN"];
      let result = dict[key] ?? key;
      if (vars) {
        Object.entries(vars).forEach(([k, v]) => {
          result = result.replace(new RegExp(`\\{${k}\\}`, "g"), String(v));
        });
      }
      return result;
    },
    [settings.language]
  );

  return (
    <SettingsContext.Provider
      value={{ settings, updateSettings, resetSettings, t }}
    >
      {children}
    </SettingsContext.Provider>
  );
};

export function useSettings(): SettingsContextValue {
  const ctx = useContext(SettingsContext);
  if (!ctx) throw new Error("useSettings must be used within SettingsProvider");
  return ctx;
}
